apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: test
spec:
  inputs:
    resources:
      - name: pr
        type: pullRequest
    params:
      - name: status
        type: string
  outputs:
    resources:
      - name: pr
        type: pullRequest
  steps:
    - name: run-test
      image: golang:1.14-alpine
      command: ["bash"]
      args:
        - -c
        - |
          set -ex
          cp -r /workspace/pr/ /workspace/output/
          set +e
          go test
          exit_code=$?
          set -e
          if [[ $exit_code -ne 0 ]]; then
            code="failure"
            echo "Test failure!" > /workspace/output/pr/comments/new
            echo "Logs:" >> /workspace/output/pr/comments/new
            echo $out >> /workspace/output/pr/comments/new
          else
            code="success"
          fi
          cat <<EOF > /workspace/output/pr/status/tekton.json
          {
            "ID": "gotest",
            "Code": "$code",
            "Description": "Gotest"
          }
          EOF
